version: '3.7'

services:
  web:
    build: ./farm_shop
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./farm_shop/:/usr/src/farm_shop/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=adik19
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=farm_django_db

volumes:
  postgres_data: