version: '3.7'

services:
  web:
    build:
      context: ./farm_shop
      dockerfile: Dockerfile.prod
    restart: always
    command: gunicorn farm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/farm_shop/web/static
      - media_volume:/home/farm_shop/web/media
    expose:
      - 8000  
    env_file:
      - ./.env.prod
    depends_on:
      - db
      
  db:
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/farm_shop/web/static
      - media_volume:/home/farm_shop/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: